### ISSUE TITLE
学生页面文档：公益时记录详情页

### ISSUE THREAD

**Issue by Nouzan** [SYSU-MATHZH/Dedekind-Django#10]

**Comment by CanDoge** [comment]
2

**Comment by CanDoge** [comment]
# 需要实现的功能
1.查看公益时申请记录详情
2.（转跳到）个人主页，个人信息管理页，**导出公益时记录列表**

#  如何实现
## 功能1：查看公益时申请记录详情
### 目标效果：
.在页面展示该用户的公益时申请记录详情，包括序号、申请日期、活动名称、举办单位、公益时数、（申请）是否通过

### 后台如何实现
查询提取并显示所需要的信息

### 网页如何实现
表格第一行：序号、申请日期、活动名称、举办单位、公益时数、（申请）是否通过
接下来的几行展示查询得到的信息。	

### 提供给网页的资源


## 功能2：（转跳到）个人主页，个人信息管理页，导出公益时记录列表
### 实现：
设置按钮链接到相关页面即可
