### ISSUE TITLE
学生页面文档：提出申诉页

### ISSUE THREAD

**Issue by Nouzan** [SYSU-MATHZH/Dedekind-Django#5]

**Comment by licnalin** [comment]
！

**Comment by licnalin** [comment]
提出申诉页  
# 需要实现的功能：
>1. 展示申诉人信息及被申诉活动名称等详情
>2. 填写申诉内容并提交
# 目标效果：
>1. 展示申诉人个人信息如姓名，学号。展示申诉日期
>2. 展示被申诉活动名称及活动日期，以及申诉受理方
>3. 可以填写申诉内容，并提交申诉
# 后台如何实现：
>先判断这个申诉是否存在，是否过了公示期，查询该学生及活动相关信息，提供给模板代码使用。

# 网页如何实现：
>1. 网页最上方显示发起对某某活动的申诉。下面分四行显示相关信息，详情的信息显示在标题的下面。第一行是申诉人姓名，学号，申诉日期，学年度。第二行是活动名称，活动日期。第三行是活动受理方。
>2.第四行是申诉内容，下面有个方框可以填写申诉内容，方框下面有个提交申诉的按钮。
