### ISSUE TITLE
学生页面文档：申诉详情页

### ISSUE THREAD

**Issue by Nouzan** [SYSU-MATHZH/Dedekind-Django#6]

**Comment by licnalin** [comment]
！

**Comment by licnalin** [comment]
# 需要实现的功能：
>1 显示申诉记录
>2 查看详细申诉结果
# 目标效果：
>展示申诉的详情，包括申诉日期，申诉项目，审批状态。
# 后台实现：
>

# 网页如何实现：
>按申诉时间顺序展示申诉的详情，包括申诉日期，申诉项目，审批状态。横向标题是，序号，申诉日期，申请项目，审批状态。
