### ISSUE TITLE
学生页面文档：个人信息详情页

### ISSUE THREAD

**Issue by Nouzan** [SYSU-MATHZH/Dedekind-Django#7]

**Comment by Demonhero0** [comment]
1

**Comment by Demonhero0** [comment]
[个人信息详情页.txt](https://github.com/SYSU-MATHZH/Dedekind-Django/files/1669813/default.txt)

**Comment by Demonhero0** [comment]
个人信息详情页

功能一、需要展示的信息
1、学号姓名
2、年级专业  班别
3、出生日期
4、性别
5、个人爱好/特长
6、职位（社团、团学传）
7、状态
8、当前校区
9、当前学年学期

目标效果：
	1、将学生的个人信息简洁地展示出来，可以将所有的信息直接展现出来
	2、学生可对自己的信息创建、编辑、删除、查看
	3、学院可对信息进行创建、编辑、删除、查看
	
实现方法：
	建立数据库，存储每个学生的资料，在打开此页面时将信息展出，
	可参考“中山大学教务系统代码”（暂无具体操作）
	
功能二、跳转回个人主页
目标效果：在网页最后下方创建一个回到个人主页的按钮。
