### ISSUE TITLE
学生页面文档：导出公益时记录页

### ISSUE THREAD

**Issue by Nouzan** [SYSU-MATHZH/Dedekind-Django#8]

**Comment by augusworkspace** [comment]
3

**Comment by augusworkspace** [comment]
3

**Comment by augusworkspace** [comment]
_1.  功能
能将公益时详情整合为pdf，以供下载

2. 目标
让用户能够将自己的公益时详情记录下载为pdf文件

3. 效果
在用户主页公益时详情栏处下方添加**下载为pdf**按钮，是其能够下载详情表

4. 后台如何实现
当用户点击按钮时，启用views内的download函数，获取用户所属的公益时数据，运用reportlab库内的函数整合为表单，而后生成pdf，让用户下载

5.网页实现
在用户主页处公益时详情栏下方添加**下载为pdf**按钮_
