### ISSUE TITLE
学生页面文档：提交公益时申请页

### ISSUE THREAD

**Issue by Nouzan** [SYSU-MATHZH/Dedekind-Django#9]

**Comment by CanDoge** [comment]
3

**Comment by CanDoge** [comment]
# 需要实现的功能
1.创建、填写、提交公益时申请
2.（转跳到）个人主页，个人信息管理页

#  如何实现
## 功能1：创建、填写、提交公益时申请
### 目标效果：
1.展示学生姓名、学号、申请日期、学年度
2.由用户填写活动名称、活动日期、活动详情、活动组织方、负责人联系方式、参与组别、公益时数
3.由用户上传本地的公益时证明材料文件（显示“选择文件”按钮）

### 后台如何实现
收到提交（POST）请求后，将用户填入的表单信息处理，再将从表单中获取的信息保存，供给模板使用。

### 网页如何实现
将学生姓名、学号、申请日期、学年度以表格形式展示，建立用户填写（活动名称、活动日期、活动详情、活动组织方、负责人联系方式、参与组别、公益时数）的表格，显示“线下证明”、“选择文件”、“提交”按钮

### 提供给网页的资源


## 功能2：（转跳到）个人主页，个人信息管理页
### 实现：
设置按钮链接到相关页面即可
